[workspace]
resolver = "2"
members = [ "snake", "flames" , "neoplay" ]

[workspace.dependencies]
neotron-sdk = "0.2"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
debug = true
codegen-units = 1
