name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Check Syntax
        run: |
          cargo check
 
      - name: Test
        run: |
          cargo test --lib

      - name: Install Targets and Tools
        run: |
          rustup target add thumbv6m-none-eabi
          rustup target add thumbv7m-none-eabi
          rustup target add thumbv7em-none-eabi
          rustup component add llvm-tools
         
      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binutils@0.3.6

      - name: Build
        run: |
          cargo build --release
          cargo build --release --target=thumbv6m-none-eabi
          cargo build --release --target=thumbv7m-none-eabi
          cargo build --release --target=thumbv7em-none-eabi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{success()}}
        with:
          name: Artifacts
          if-no-files-found: error
          path: |
            ./target/release/snake
            ./target/*/release/snake
            ./target/release/flames
            ./target/*/release/flames

      - name: Upload files to Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/release/snake
            ./target/*/release/snake
            ./target/release/flames
            ./target/*/release/flames
